### ISSUE TITLE
dupree checks a->b and b->a

### ISSUE THREAD

**Issue by Alanocallaghan** [russHyde/dupree#29]
I noticed in the presentation that every result is presented twice; once as a-> and again as b->a (where -> denotes "is most similar"). I don't think doing a one vs all for every block is the right approach, although when you reduce the problem to comparison of int vectors it's probably not too bad.

What I would do (see PR) is do only the unique combinations, then filter those results somehow. The way I've done in the PR is a bit off, so take it with a grain of salt.

btw the thought occurs - how well does this approach of tokenisation work when you have more than 10 symbols? Seems like that might mess with the similarity quite a bit as "1" "6" then becomes the same as "16"

**Comment by russHyde** [comment]
What dupree does (at present) is as follows:
- for each block X
     - find the block Y with the highest similarity to X
     - add X -> Y to the results dataframe

So if X -> Y is the highest scoring block pair across a set of files, then Y -> X will always be present.
But, there could be a block Z within the files such that it's closest match is X.

Nonetheless, I think you are right, it makes sense to only return unique pairs. I'll have a look at the PR in a bit.

Re the sequence alignment, code symbols are converted to `int` not to `character`, so the tokenised vector is like [1, 6, 16] rather than "1616", "1,6,16" or ["1", "6", "16"]. And the integer vectors are aligned using exact matching / the discrete metric: 1 is no closer to 16 than it is to 2. Have a look at the docs for `stringdist::seq_sim` (https://www.rdocumentation.org/packages/stringdist/versions/0.9.5.1/topics/seq_sim). This means there's no practical limit to how many code symbols can be tokenised (unless you're hitting 2147483647 symbols, that is - suspect simply holding the codebase in memory will bite dupree's efficacy by that point).

ps, I did think that I should provide the user the opportunity to choose how many similar-blocks should be returned for each input block

**Comment by Alanocallaghan** [comment]
Ah yes sorry, I did actually eyeball the sequences but forgot that they're left as vectors rather than concatenated.

Seems like allowing a filter based on number and/or max similarity makes more sense than just the max similarity - currently (and with my PR) you could have a network of quite similar blocks that get ignored because they're not most similar to anything.
